apiVersion: v1
kind: Secret
metadata:
  name: consultation-secret
  namespace: esante-cmr
type: Opaque
data:
  username: Y29uc3VsdGF0aW9uX3VzZXI=  # consultation_user
  password: Y29uc3VsdGF0aW9uX3Bhc3M=  # consultation_pass
